config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   root to: 'videos#index'

   resources :videos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/video.rb
class Video
  attr_reader :title, :thumbnails, :short_description, :_id, :description, :youtube_id
  def initialize options={}
    options.each do |k, v|
      eval("@#{k.to_s} = v")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    @videos = Zype::Videos.new.fetch_list(page: params[:page])
    @pagination = @videos['pagination']
    @videos = @videos['response'].map{|vid| Video.new(vid)}
  end

  def show
    @video = Zype::Videos.new(video_id: params[:id]).fetch_video
    @video = Video.new(@video['response'])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vidoes_helper.rb
module VidoesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZypeApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/videos/_video.html.erb
<div class="container video_popup" id="popup_<%= @video._id %>">
  <button type="button" class="close cancel-btn" data-dismiss="modal">&times;</button>
  <div class="card" id="video_<%= @video._id %>">
    <div class="card-body">
      <div class="row img_and_data">
        <div class="col-8 image">
          <div id="zype_<%= @video.youtube_id %>"></div>
          <script src="https://player.zype.com/embed/<%= @video.youtube_id %>.js?autoplay=true&app_key=<%= ENV.fetch('ZYPE_APP_KEY') %>" type="text/javascript"></script>
        </div>
        <div class="col-4 title_desc">
          <code class="title" data-id="<%= @video._id %>"><%= @video.title %></code>
          <p class="description"><%= @video.description  %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/videos/_videos.html.erb
<% @videos.each_slice(3).to_a.each_with_index do |videos_group, indx1| %>
  <div class="card-deck" id="row_<%= 1 + indx1/3 %>">
    <% videos_group.each_with_index do |video, indx2| %>
      <div class="card" id="video_<%= video._id %>">
        <div class="card-body">
          <div class="row img_and_data">
            <div class="col-4 image">
              <img src="<%= video.thumbnails.first['url'] %>" width="100%" data-id="<%= video._id %>">
            </div>
            <div class="col-8 title_desc">
              <code class="title" data-id="<%= video._id %>"><%= truncate(video.title, length: 30) %></code>
              <p class="short_description"><%= truncate(video.short_description, length: 200)  %></p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>
<div class="row">
  <div class="col-6 text-left">
    <% if @pagination['previous'].to_i > 0 %>
      <%= link_to "<< Prev", videos_path(page: @pagination['previous']), class: 'btn btn-warning', 'data-remote': true %>
    <% end %>
  </div>
  <div class="col-6 text-right">
    <% if @pagination['next'].to_i > params[:page].to_i %>
      <%= link_to "Next >>", videos_path(page: @pagination['next']), class: 'btn btn-info', 'data-remote': true %>
    <% end %>
  </div>
</div>

app/views/videos/index.html.erb
<div class="container main">
  <%= render 'videos' %>
</div>

app/views/videos/index.js.erb
$('.container.main').html("<%= j(render partial: 'videos') %>")

app/views/videos/show.js.erb
$(".container.video_popup").hide('slow').remove()
$("#video_<%= @video._id %>").parent('div.card-deck').after("<%= j(render partial: 'video') %>")
$("#popup_<%=@video._id%>").show('slow')